server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://127.0.0.1:8761/eureka

greeting:
  message: "Welcome to the Simple E-commerce"

spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3  #  ??? ?? ??? 3?? ???
      max-lifetime: 580000
      pool-name: Hikari
      read-only: false
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
#    url: jdbc:log4jdbc:mysql://localhost:3306/springframework?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: as!234
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2
