server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://127.0.0.1:8761/eureka

greeting:
  message: "Welcome to the Simple E-commerce"

spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 3
      max-lifetime: 580000
      pool-name: Hikari
      read-only: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 테이블 대문자
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: as!234

logging:
  level:
    com.example.userservice: debug

